![Imgur](https://i.imgur.com/h4PPC71.png)
#**10-modul. Maʼlumotlarga ishlov berish. Fayllar va maʼlumotlar ombori**

#**10.25. Modul boʻyicha yakuniy amaliy vazifa**

**Amaliyotni bajargach, fayllar bilan ishlash, API va veb sahifalardan ma’lumot olish, SQL soʻrovlarini yozish va ma’lumotlar omboriga ma’lumot saqlash koʻnikmalariga ega boʻlasiz.**

#**Fayldan oʻqish va yozish**

#**1) CSV fayldan maʼlumotlarni o‘qish**
* https://raw.githubusercontent.com/alishermutalov/praktikum-datasets/refs/heads/praktikum/data_date.csv havolasidagi maʼlumotlarni `df` oʻzgaruvchisiga saqlang!
* `df` dan tasodifiy 10 ta qatorni ekranga chiqaring!

In [1]:
import pandas as pd
import sqlite3 as sql

df=pd.read_csv("https://raw.githubusercontent.com/alishermutalov/praktikum-datasets/refs/heads/praktikum/data_date.csv")
df.head(15)

          Date     Country                          Status  AQI Value
0   2022-07-21     Albania                            Good         14
1   2022-07-21     Algeria                        Moderate         65
2   2022-07-21     Andorra                        Moderate         55
3   2022-07-21      Angola  Unhealthy for Sensitive Groups        113
4   2022-07-21   Argentina                        Moderate         63
5   2022-07-21     Armenia                        Moderate         76
6   2022-07-21   Australia                        Moderate         56
7   2022-07-21     Austria                            Good         45
8   2022-07-21  Azerbaijan                            Good         12
9   2022-07-21     Bahrain                       Unhealthy        165
10  2022-07-21  Bangladesh  Unhealthy for Sensitive Groups        141
11  2022-07-21     Belarus                            Good         13
12  2022-07-21     Belgium                        Moderate         61
13  2022-07-21      Belize                            Good         28
14  2022-07-21     Bermuda                            Good         12

#**2) CSV fayliga yozish**
* Quyidagi maʼlumotlardan dataframe yarating va uni `people_data.csv` fayliga saqlang.
```
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve", "Frank", "Grace", "Hannah", "Ivy", "Jack"],
    "Age": [25, 30, 35, 40, 28, 33, 38, 45, 29, 31],
    "City": ["Tashkent", "Samarkand", "Bukhara", "Andijan", "Nukus", "Khiva", "Namangan", "Fergana", "Jizzakh", "Termez"]
}
```
* Quyidagi maʼlumotlardan yana bir dataframe yarating va uni `people_data_2.csv` fayliga saqlang.
```
{
'Name': ['Alice', 'Bob', 'Charlie'],
'Age': [25, 30, 35]
}
```

In [2]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve", "Frank", "Grace", "Hannah", "Ivy", "Jack"],
    "Age": [25, 30, 35, 40, 28, 33, 38, 45, 29, 31],
    "City": ["Tashkent", "Samarkand", "Bukhara", "Andijan", "Nukus", "Khiva", "Namangan", "Fergana", "Jizzakh", "Termez"]
}
df1=pd.DataFrame(data)

df1.to_csv("people_data.csv", index=False)
df1

data2={
'Name': ['Alice', 'Bob', 'Charlie'],
'Age': [25, 30, 35]
}
df2=pd.DataFrame(data2)
df2.to_csv("people_data_2.csv", index=False)
df2

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

#**3) HDF5 formati bilan ishlash**
* Yuqorida yaratgan dataframeʼlaringizni `people.h5` faylida saqlang.
* `people.h5` faylidagi barcha jadvallarni oʻqing!

In [3]:
hdfobj=pd.HDFStore("people.h5")
hdfobj.put("people",df1)
hdfobj.put("user",df2)

In [4]:
hdfobj.keys()

['/people', '/user']

In [5]:
hdfobj['people']

      Name  Age       City
0    Alice   25   Tashkent
1      Bob   30  Samarkand
2  Charlie   35    Bukhara
3    David   40    Andijan
4      Eve   28      Nukus
5    Frank   33      Khiva
6    Grace   38   Namangan
7   Hannah   45    Fergana
8      Ivy   29    Jizzakh
9     Jack   31     Termez

In [6]:
hdfobj['user']

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

In [7]:
hdfobj.close()

#**4) JSON fayllar bilan ishlash**
1. Quyidagi maʼlumotlarni dataframe koʻrinishida oʻqing va uni `data.json` fayliga yozing!
```
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve", "Frank", "Grace", "Hannah", "Ivy", "Jack"],
    "Age": [25, 30, 35, 40, 28, 33, 38, 45, 29, 31],
    "City": ["Tashkent", "Samarkand", "Bukhara", "Andijan", "Nukus", "Khiva", "Namangan", "Fergana", "Jizzakh", "Termez"]
}
```

In [9]:
data3 = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve", "Frank", "Grace", "Hannah", "Ivy", "Jack"],
    "Age": [25, 30, 35, 40, 28, 33, 38, 45, 29, 31],
    "City": ["Tashkent", "Samarkand", "Bukhara", "Andijan", "Nukus", "Khiva", "Namangan", "Fergana", "Jizzakh", "Termez"]
}
df3=pd.DataFrame(data3)
df3.to_json("data.json")
df3

      Name  Age       City
0    Alice   25   Tashkent
1      Bob   30  Samarkand
2  Charlie   35    Bukhara
3    David   40    Andijan
4      Eve   28      Nukus
5    Frank   33      Khiva
6    Grace   38   Namangan
7   Hannah   45    Fergana
8      Ivy   29    Jizzakh
9     Jack   31     Termez

#**5) APIʼlar bilan ishlash**
1. Quyida berilgan API 17 mingdan ortiq kriptovalyutalarning dollarga nisbatan narxi haqidagi maʼlumotlarni saqlaydi. Siz esa endi:
  * API orqali barcha maʼlumotlarni yigʻib oling;
  * ularni dataframe koʻrinishida saqlang;
  * maʼlumotlar boshidan 5 ta qatorni ekranga chiqaring;
  * maʼlumotlar ichidan `bitcoin` ni izlab toping!

In [11]:
coins_url = "https://api.coingecko.com/api/v3/coins/list"
df4=pd.read_json(coins_url)
df4.head(5)

,id,symbol,name
0,_,gib,༼ つ ◕_◕ ༽つ
1,000-capital,000,000 Capital
2,01111010011110000110001001110100-token,01111010011110000110001001110100,01111010011110000110001001110100
3,01112131415161718192021222324252-token,1234567891,01112131415161718192021222324252
4,01-token,01,01

In [12]:
bitcoin_data=df4[df4['id']=='bitcoin']
bitcoin_data

           id symbol     name
2701  bitcoin    btc  Bitcoin

#**6) APIʼlar bilan ishlash**
1. Yuqorida berilgan kriptovalyuta maʼlumotlaridan `id` ustunini roʻyxat koʻrinishida saqlang va bu roʻyxatga `coin_ids` deb nom bering.
2. https://api.coingecko.com/api/v3/simple/price?ids={coin_ids}&vs_currencies=usd havolasi orqali kriptovalyutalarning `usd` ga nisbatini oling (birinchi 100 ta maʼlumotni olish yetarli).
3. 2-shartda berilgan link orqali olingan maʼlumotlarni dataframe koʻrinishida saqlang. Bunda uning indeksi va `usd` ustuni boʻlsin. `index` -> kriptovalyutalar nomi, `usd` -> narxi

#**💡Ishora:** linkdagi `{coin_ids}` oʻzgaruvchi sifatida yozilgan. Siz ham 1-shartda saqlagan `coin_ids` oʻzgaruvchingizni shu qismda yozib keting!

In [14]:
coin_ids = ",".join(df4['id'].tolist()[:100])
price_url = (f"https://api.coingecko.com/api/v3/simple/price?ids={coin_ids}&vs_currencies=usd")
df_price=pd.read_json(price_url).T
df_price.head()
#javobni shu yerda yozing

                                             usd
_                                       0.001835
000-capital                             0.000012
01111010011110000110001001110100-token  0.000013
01112131415161718192021222324252-token  0.000004
01-token                                0.000037

#**7) Veb sahifadan oʻqish**
1. Pandas yordamida veb sahifadagi jadvalni yuklab oling.
2. Ma’lumotlarni dataframe ko‘rinishida chiqaring.
3. Agar sahifada bir nechta jadval bo‘lsa, eng muhimini tanlang.
4. Ma’lumotni tozalang (bo‘sh qatorlarni olib tashlang, kerakli ustunlarni tanlang).
5. Natijani CSV faylga saqlang.

***Eslatma: manba sifatida oʻzingiz istagan veb sahifani tanlang. Bu vazifada mustaqil izlanishni oʻrganasiz!***

In [21]:
import pandas as pd
import requests

headers = {
    'User-Agent': (
        'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,'
        ' like Gecko) Chrome/122.0.0.0 Safari/537.36'
    )
}

url = 'https://en.wikipedia.org/wiki/London'

response = requests.get(url, headers=headers)#sahifani yuklab olaman

tables = pd.read_html(response.text)

df_web = tables[0]
df_web=df_web.dropna()#ma'lumotlarni tozalash
df_web.to_csv("london.csv", index=False)
df_web

/tmp/ipykernel_1960/2647484798.py:15: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(response.text)

,London,London.1
0,Capital city,Capital city
1,River Thames and Tower Bridge with The Shard a...,River Thames and Tower Bridge with The Shard a...
2,"Map of the Greater London administrative area,...","Map of the Greater London administrative area,..."
3,LondonLocation within EnglandLondonLocation wi...,LondonLocation within EnglandLondonLocation wi...
4,Coordinates: 51°30′26″N 0°7′39″W﻿ / ﻿51.50722°...,Coordinates: 51°30′26″N 0°7′39″W﻿ / ﻿51.50722°...
5,Sovereign state,United Kingdom
6,Country,England
7,Region,London
8,Ceremonial counties,Greater LondonCity of London
9,Settled by Romans,"AD 47; 1979 years ago, as Londinium[1]"
10,Administrative HQ,City Hall
11,Local government,"32 London boroughs, the City of London and Que..."
12,Government,Government
13,• Type,Executive mayoralty and deliberative assembly
14,• Body,Greater London Authority
15,• Mayor,Sadiq Khan (L)
16,• London Assembly,14 constituencies
17,• UK Parliament,74 constituencies
18,Area[2],Area[2]
19,• Total[a],"607 sq mi (1,572 km2)"
20,• Urban,"671 sq mi (1,738 km2)"
21,• Metro,"3,236 sq mi (8,382 km2)"
22,Population (2025)[2],Population (2025)[2]
23,• Total[b],9122909
24,• Rank,1st in the UK3rd in Europe
25,• Density,"15,030/sq mi (5,804/km2)"
26,• Urban (2021)[3],10558797
27,• Metro[c] (2026)[4],15400000
28,Demonyms,Londoner
29,Ethnicity (2021)[5],Ethnicity (2021)[5]
30,• Ethnic groups,List 53.8% White 20.7% Asian 13.5% Black 6...
31,Religion (2021)[5],Religion (2021)[5]
32,• Religion,List 40.7% Christianity 27.1% no religion 1...
33,Time zone,UTC+00:00 (GMT)
34,• Summer (DST),UTC+01:00 (BST)
35,Postcode areas,"22 areas E, EC, N, NW, SE, SW, W, WC, BR, CM, ..."
36,Dialling codes,020016890170801895
37,GSS code,E12000007 (region)E61000001 (GLA)
38,GeoTLD,.london
39,Website,london.gov.uk

# **Maʼlumotlar ombori bilan ishlash**

#**8) Maʼlumotlar omborini yuklash va ulanish**
1. https://github.com/alishermutalov/praktikum-datasets/blob/praktikum/chinook.db havolasi orqali maʼlumotlar omborini yuklab oling.
2. Yuklab olingan maʼlumotlar omboriga sqlite3 moduli yordamida **ulaning**.

In [22]:
!wget https://www.sqlitetutorial.net/wp-content/uploads/2018/03/chinook.zip
!unzip "chinook.zip"

--2026-10-20 10:23:57--  https://www.sqlitetutorial.net/wp-content/uploads/2018/03/chinook.zip
Resolving www.sqlitetutorial.net (www.sqlitetutorial.net)... 104.21.30.141, 172.67.172.250, 2606:4700:3031::6815:1e8d, ...
Connecting to www.sqlitetutorial.net (www.sqlitetutorial.net)|104.21.30.141|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 305596 (298K) [application/zip]
Saving to: ‘chinook.zip’

chinook.zip         100%[===================>] 298.43K  --.-KB/s    in 0.03s

2026-10-20 10:23:58 (10.2 MB/s) - ‘chinook.zip’ saved [305596/305596]

Archive:  chinook.zip
  inflating: chinook.db

In [29]:
import sqlite3 as sql
conn = sql.connect('chinook.db')

   AlbumId                                  Title  ArtistId
0        1  For Those About To Rock We Salute You         1
1        2                      Balls to the Wall         2
2        3                      Restless and Wild         2
3        4                      Let There Be Rock         1
4        5                               Big Ones         3

#**9) Maʼlumotlar omboriga soʻrov yuborish**
1. Jadvallar roʻyxatini koʻring. Ularning ichida `albums` jadvali boʻlsa, shu jadvaldagi barcha maʼlumotlarni (qatorlarni) ekranga chiqaring.
2. Qatorlar soni nechta ekanini aniqlab, uni ham ekranga chiqaring.
3.`albums` jadvalining ustunlari haqidagi maʼlumotlarni ekranga chiqaring.

In [35]:
cursor=conn.cursor()
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
cursor.fetchall()

[('albums',),
 ('sqlite_sequence',),
 ('artists',),
 ('customers',),
 ('employees',),
 ('genres',),
 ('invoices',),
 ('invoice_items',),
 ('media_types',),
 ('playlists',),
 ('playlist_track',),
 ('tracks',),
 ('sqlite_stat1',)]

In [34]:
cursor.execute("SELECT COUNT (*) FROM albums")
cursor.fetchall()

[(347,)]

In [32]:
df = pd.read_sql('SELECT * FROM albums ;', conn)
df

     AlbumId                                              Title  ArtistId
0          1              For Those About To Rock We Salute You         1
1          2                                  Balls to the Wall         2
2          3                                  Restless and Wild         2
3          4                                  Let There Be Rock         1
4          5                                           Big Ones         3
..       ...                                                ...       ...
342      343                             Respighi:Pines of Rome       226
343      344  Schubert: The Late String Quartets & String Qu...       272
344      345                                Monteverdi: L'Orfeo       273
345      346                              Mozart: Chamber Music       274
346      347  Koyaanisqatsi (Soundtrack from the Motion Pict...       275

[347 rows x 3 columns]

#**10) SQL to DataFrame**
1. `albums` jadvalini `pandas.DataFrame` ga oʻtkazing!

In [37]:
df = pd.read_sql('SELECT * FROM albums ;', conn)
df.head()

   AlbumId                                  Title  ArtistId
0        1  For Those About To Rock We Salute You         1
1        2                      Balls to the Wall         2
2        3                      Restless and Wild         2
3        4                      Let There Be Rock         1
4        5                               Big Ones         3

#**11)**  `chinook.db` maʼlumotlar omboridan `tracks` jadvalining birinchi 10 ta qatorini ekranga chiqaring

#💡Ishora: LIMIT

In [39]:
df=pd.read_sql("SELECT * FROM tracks LIMIT 10",conn)
df

,TrackId,Name,AlbumId,MediaTypeId,GenreId,Composer,Milliseconds,Bytes,UnitPrice
0,1,For Those About To Rock (We Salute You),1,1,1,"Angus Young, Malcolm Young, Brian Johnson",343719,11170334,0.99
1,2,Balls to the Wall,2,2,1,None,342562,5510424,0.99
2,3,Fast As a Shark,3,2,1,"F. Baltes, S. Kaufman, U. Dirkscneider & W. Ho...",230619,3990994,0.99
3,4,Restless and Wild,3,2,1,"F. Baltes, R.A. Smith-Diesel, S. Kaufman, U. D...",252051,4331779,0.99
4,5,Princess of the Dawn,3,2,1,Deaffy & R.A. Smith-Diesel,375418,6290521,0.99
5,6,Put The Finger On You,1,1,1,"Angus Young, Malcolm Young, Brian Johnson",205662,6713451,0.99
6,7,Let's Get It Up,1,1,1,"Angus Young, Malcolm Young, Brian Johnson",233926,7636561,0.99
7,8,Inject The Venom,1,1,1,"Angus Young, Malcolm Young, Brian Johnson",210834,6852860,0.99
8,9,Snowballed,1,1,1,"Angus Young, Malcolm Young, Brian Johnson",203102,6599424,0.99
9,10,Evil Walks,1,1,1,"Angus Young, Malcolm Young, Brian Johnson",263497,8611245,0.99

#**12)**`tracks` jadvalidan faqat `Name`, `Composer` ustunlarini tanlab oling!

In [40]:
df=pd.read_sql("SELECT Name, Composer FROM tracks", conn)
df

,Name,Composer
0,For Those About To Rock (We Salute You),"Angus Young, Malcolm Young, Brian Johnson"
1,Balls to the Wall,None
2,Fast As a Shark,"F. Baltes, S. Kaufman, U. Dirkscneider & W. Ho..."
3,Restless and Wild,"F. Baltes, R.A. Smith-Diesel, S. Kaufman, U. D..."
4,Princess of the Dawn,Deaffy & R.A. Smith-Diesel
...,...,...
3498,Pini Di Roma (Pinien Von Rom) \ I Pini Della V...,None
3499,"String Quartet No. 12 in C Minor, D. 703 ""Quar...",Franz Schubert
3500,"L'orfeo, Act 3, Sinfonia (Orchestra)",Claudio Monteverdi
3501,"Quintet for Horn, Violin, 2 Violas, and Cello ...",Wolfgang Amadeus Mozart
3502,Koyaanisqatsi,Philip Glass

#**13) ORDER BY , DISTINCT**
* `tracks` jadvalidagi takrorlanmaydigan `GenreId` qiymatlarini oling.
* `tracks` jadvalidagi treklarni `Milliseconds` ustuni bo‘yicha kamayish tartibida saralang.

#💡Ishora: ORDER BY , DISTINCT

In [41]:
query="SELECT DISTINCT GenreId FROM tracks"
df=pd.read_sql(query,conn)
df

    GenreId
0         1
1         2
2         3
3         4
4         5
5         6
6         7
7         8
8         9
9        10
10       11
11       12
12       13
13       14
14       15
15       16
16       17
17       18
18       19
19       20
20       21
21       22
22       23
23       24
24       25

In [43]:
komanda="SELECT Milliseconds FROM tracks ORDER BY Milliseconds DESC"
df=pd.read_sql(komanda,conn)
df

      Milliseconds
0          5286953
1          5088838
2          2960293
3          2956998
4          2956081
...            ...
3498          7941
3499          6635
3500          6373
3501          4884
3502          1071

[3503 rows x 1 columns]

#**14) Filtering**
 * `invoices` jadvalidan `Total` summasi 10 dan katta bo‘lgan maʼlumotlarni tanlang.

# 💡Ishora: WHERE

In [49]:
query='SELECT * FROM invoices WHERE Total>10'
df=pd.read_sql(query,conn)
df

,InvoiceId,CustomerId,InvoiceDate,BillingAddress,BillingCity,BillingState,BillingCountry,BillingPostalCode,Total
0,5,23,2009-01-11 00:00:00,69 Salem Street,Boston,MA,USA,2113,13.86
1,12,2,2009-02-11 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,13.86
2,19,40,2009-03-14 00:00:00,"8, Rue Hanovre",Paris,None,France,75002,13.86
3,26,19,2009-04-14 00:00:00,1 Infinite Loop,Cupertino,CA,USA,95014,13.86
4,33,57,2009-05-15 00:00:00,"Calle Lira, 198",Santiago,None,Chile,None,13.86
...,...,...,...,...,...,...,...,...,...
59,383,10,2013-08-12 00:00:00,"Rua Dr. Falcão Filho, 155",São Paulo,SP,Brazil,01007-010,13.86
60,390,48,2013-09-12 00:00:00,Lijnbaansgracht 120bg,Amsterdam,VV,Netherlands,1016,13.86
61,397,27,2013-10-13 00:00:00,1033 N Park Ave,Tucson,AZ,USA,85719,13.86
62,404,6,2013-11-13 00:00:00,Rilská 3174/6,Prague,None,Czech Republic,14300,25.86
63,411,44,2013-12-14 00:00:00,Porthaninkatu 9,Helsinki,None,Finland,00530,13.86

#**15) CREATE and INSERT**
* `chinook.db` maʼlumotlar omboriga `users` jadvali yarating. Foydalanuvchilarning har biri uchun berilgan yosh qiymatlaridan foydalanib, birth_date ustunini to‘ldirish strategiyasini ishlab chiqing va amalda qo‘llang. Jadval maydonlari (ustunlar):
  * `id`
  * `name`
  * `birth_date`
* Yaratilgan `users` jadvaliga quyidagi maʼlumotlarni qoʻshing:

    * ```
    [
    ('Alice', 25), ('Bob', 30), ('Charlie', 35), ('David', 28), ('Eve', 22),
    ('Frank', 40), ('Grace', 27), ('Hannah', 32), ('Ivy', 29), ('Jack', 31),
    ('Kevin', 33), ('Liam', 26), ('Mia', 24), ('Noah', 36), ('Olivia', 23),
    ('Peter', 39), ('Quinn', 37), ('Rachel', 34), ('Samuel', 41), ('Tina', 21)
]
 ```

#💡Ishora: CREATE TABLE, INSERT

In [51]:
users="""
CREATE TABLE IF NOT EXISTS birth_date(
id INTEGER PRIMARY KEY AUTOINCREMENT,
name TEXT NOT NULL,
birth_date INTEGER NOT NULL
)"""
cursor.execute(users)
conn.commit()

In [59]:
users = """INSERT INTO birth_date VALUES
(1, 'Alice', 25), (2, 'Bob', 30), (3, 'Charlie', 35), (4, 'David', 28), (5, 'Eve', 22),
(6, 'Frank', 40), (7, 'Grace', 27), (8, 'Hannah', 32), (9, 'Ivy', 29), (10, 'Jack', 31),
(11, 'Kevin', 33), (12, 'Liam', 26), (13, 'Mia', 24), (14, 'Noah', 36), (15, 'Olivia', 23),
(16, 'Peter', 39), (17, 'Quinn', 37), (18, 'Rachel', 34), (19, 'Samuel', 41), (20, 'Tina', 21);"""

cursor.execute(users)
conn.commit()

#**16) UPDATE and DELETE**
* `users` jadvalidagi Alice ismli foydalanuvchining yoshini yangilang.
* `users` jadvalidan Alice ismli foydalanuvchini o‘chiring.

In [61]:
users="UPDATE birth_date SET birth_date=28 WHERE name='Alice'"
cursor.execute(users)
conn.commit()

In [62]:
users="DELETE FROM birth_date WHERE name='Alice'"
cursor.execute(users)
conn.commit()

In [64]:
df=pd.read_sql("SELECT * FROM birth_date",conn)
df

    id     name  birth_date
0    2      Bob          30
1    3  Charlie          35
2    4    David          28
3    5      Eve          22
4    6    Frank          40
5    7    Grace          27
6    8   Hannah          32
7    9      Ivy          29
8   10     Jack          31
9   11    Kevin          33
10  12     Liam          26
11  13      Mia          24
12  14     Noah          36
13  15   Olivia          23
14  16    Peter          39
15  17    Quinn          37
16  18   Rachel          34
17  19   Samuel          41
18  20     Tina          21

#**17) f-string yordamida SQL komandalarini yozish**
* `customers` jadvalidan `FirstName` va `LastName` bo‘yicha qidiruv qiladigan f-string yozing.

In [66]:
first_name = "John"
last_name = "Smith"
users=f"SELECT * FROM customers WHERE FirstName='{first_name}' AND LastName='{last_name}'"
cursor.execute(users)
conn.commit()

#**18)  AND and OR operators**

* `invoices` jadvalidan `BillingCountry` Germaniya yoki Fransiya boʻlgan va `Total` summasi 5 dan katta bo‘lgan kerakli qatorlarni tanlang.

#💡Ishora: AND, OR

In [72]:
users = "SELECT * FROM invoices WHERE (BillingCountry = 'Germany' OR BillingCountry = 'France') AND Total > 5;"
df = pd.read_sql(users, conn)
df

,InvoiceId,CustomerId,InvoiceDate,BillingAddress,BillingCity,BillingState,BillingCountry,BillingPostalCode,Total
0,12,2,2009-02-11 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,13.86
1,19,40,2009-03-14 00:00:00,"8, Rue Hanovre",Paris,None,France,75002,13.86
2,31,42,2009-05-07 00:00:00,"9, Place Louis Barthou",Bordeaux,None,France,33000,5.94
3,40,36,2009-06-15 00:00:00,Tauentzienstraße 8,Berlin,None,Germany,10789,13.86
4,52,38,2009-08-08 00:00:00,Barbarossastraße 19,Berlin,None,Germany,10779,5.94
5,67,2,2009-10-12 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,8.91
6,74,40,2009-11-12 00:00:00,"8, Rue Hanovre",Paris,None,France,75002,8.91
7,95,36,2010-02-13 00:00:00,Tauentzienstraße 8,Berlin,None,Germany,10789,8.91
8,117,41,2010-05-22 00:00:00,"11, Place Bellecour",Lyon,None,France,69002,13.86
9,129,43,2010-07-15 00:00:00,"68, Rue Jouvence",Dijon,None,France,21000,5.94
10,138,37,2010-08-23 00:00:00,Berger Straße 10,Frankfurt,None,Germany,60316,13.86
11,150,39,2010-10-16 00:00:00,"4, Rue Milton",Paris,None,France,75009,5.94
12,172,41,2011-01-20 00:00:00,"11, Place Bellecour",Lyon,None,France,69002,8.91
13,193,37,2011-04-23 00:00:00,Berger Straße 10,Frankfurt,None,Germany,60316,14.91
14,215,42,2011-07-30 00:00:00,"9, Place Louis Barthou",Bordeaux,None,France,33000,13.86
15,236,38,2011-10-31 00:00:00,Barbarossastraße 19,Berlin,None,Germany,10779,13.86
16,241,2,2011-11-23 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,5.94
17,248,40,2011-12-24 00:00:00,"8, Rue Hanovre",Paris,None,France,75002,5.94
18,269,36,2012-03-26 00:00:00,Tauentzienstraße 8,Berlin,None,Germany,10789,5.94
19,270,42,2012-03-29 00:00:00,"9, Place Louis Barthou",Bordeaux,None,France,33000,8.91
20,291,38,2012-06-30 00:00:00,Barbarossastraße 19,Berlin,None,Germany,10779,8.91
21,313,43,2012-10-06 00:00:00,"68, Rue Jouvence",Dijon,None,France,21000,16.86
22,334,39,2013-01-07 00:00:00,"4, Rue Milton",Paris,None,France,75009,13.86
23,346,41,2013-03-02 00:00:00,"11, Place Bellecour",Lyon,None,France,69002,5.94
24,367,37,2013-06-03 00:00:00,Berger Straße 10,Frankfurt,None,Germany,60316,5.94
25,368,43,2013-06-06 00:00:00,"68, Rue Jouvence",Dijon,None,France,21000,8.91
26,389,39,2013-09-07 00:00:00,"4, Rue Milton",Paris,None,France,75009,8.91

#**19) BETWEEN and LIKE**

* `invoices` jadvalidan `Total` summasi 5 dan 15 gacha bo‘lgan qatorlarni tanlang.
* `customers` jadvalidan ismi `A` harfi bilan boshlanadigan foydalanuvchilarni tanlang.

In [74]:
users="SELECT * FROM invoices WHERE Total BETWEEN 5 AND 15"
df=pd.read_sql(users,conn)
df

,InvoiceId,CustomerId,InvoiceDate,BillingAddress,BillingCity,BillingState,BillingCountry,BillingPostalCode,Total
0,3,8,2009-01-03 00:00:00,Grétrystraat 63,Brussels,None,Belgium,1000,5.94
1,4,14,2009-01-06 00:00:00,8210 111 ST NW,Edmonton,AB,Canada,T6G 2C7,8.91
2,5,23,2009-01-11 00:00:00,69 Salem Street,Boston,MA,USA,2113,13.86
3,10,46,2009-02-03 00:00:00,3 Chatham Street,Dublin,Dublin,Ireland,None,5.94
4,11,52,2009-02-06 00:00:00,202 Hoxton Street,London,None,United Kingdom,N1 5LH,8.91
...,...,...,...,...,...,...,...,...,...
163,402,50,2013-11-05 00:00:00,C/ San Bernardo 85,Madrid,None,Spain,28015,5.94
164,403,56,2013-11-08 00:00:00,307 Macacha Güemes,Buenos Aires,None,Argentina,1106,8.91
165,409,29,2013-12-06 00:00:00,796 Dundas Street West,Toronto,ON,Canada,M6J 1V1,5.94
166,410,35,2013-12-09 00:00:00,"Rua dos Campeões Europeus de Viena, 4350",Porto,None,Portugal,None,8.91
167,411,44,2013-12-14 00:00:00,Porthaninkatu 9,Helsinki,None,Finland,00530,13.86

In [80]:
users="SELECT * FROM customers WHERE firstname LIKE 'A%'"
df=pd.read_sql(users,conn)
df

,CustomerId,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,Fax,Email,SupportRepId
0,7,Astrid,Gruber,None,"Rotenturmstraße 4, 1010 Innere Stadt",Vienne,None,Austria,1010,+43 01 5134505,None,astrid.gruber@apple.at,5
1,11,Alexandre,Rocha,Banco do Brasil S.A.,"Av. Paulista, 2022",São Paulo,SP,Brazil,01310-200,+55 (11) 3055-3278,+55 (11) 3055-8131,alero@uol.com.br,5
2,32,Aaron,Mitchell,None,696 Osborne Street,Winnipeg,MB,Canada,R3L 2B9,+1 (204) 452-6452,None,aaronmitchell@yahoo.ca,4

#**20) DataFrame to SQL**
* Quyidagi maʼlumotlardan dataframe yarating.
  ```
  sales_data = {
    "sale_id": list(range(1, 21)),  # 1 dan 20 gacha boʻlgan unikal IDʼlar
    "product_name": [
        "Laptop", "Smartphone", "Tablet", "Headphones", "Smartwatch",
        "Monitor", "Keyboard", "Mouse", "Printer", "Camera",
        "Speaker", "Game Console", "TV", "Router", "Power Bank",
        "Hard Drive", "USB Flash", "Graphics Card", "Microphone", "VR Headset"
    ],
    "quantity": [2, 5, 3, 10, 4, 6, 8, 12, 3, 5, 7, 9, 4, 2, 11, 6, 15, 1, 3, 2],
    "price": [1200, 800, 450, 200, 300, 500, 100, 50, 250, 700,
              150, 400, 1000, 90, 60, 110, 30, 1500, 80, 600],
    "sale_date": [
        "2025-03-01", "2025-03-02", "2025-03-03", "2025-03-04", "2025-03-05",
        "2025-03-06", "2025-03-07", "2025-03-08", "2025-03-09", "2025-03-10",
        "2025-03-11", "2025-03-12", "2025-03-13", "2025-03-14", "2025-03-15",
        "2025-03-16", "2025-03-17", "2025-03-18", "2025-03-19", "2025-03-20"
    ]
}
```
*Yuqoridagi maʼlumotlar asosida yaratgan dataframeʼingizdan SQL jadvali tuzing va uni `sales` deb nomlang.

In [82]:
sales_data = {
    "sale_id": list(range(1, 21)),
    "product_name": [
        "Laptop",
        "Smartphone",
        "Tablet",
        "Headphones",
        "Smartwatch",
        "Monitor",
        "Keyboard",
        "Mouse",
        "Printer",
        "Camera",
        "Speaker",
        "Game Console",
        "TV",
        "Router",
        "Power Bank",
        "Hard Drive",
        "USB Flash",
        "Graphics Card",
        "Microphone",
        "VR Headset",
    ],
    "quantity": [2, 5, 3, 10, 4, 6, 8, 12, 3, 5, 7, 9, 4, 2, 11, 6, 15, 1, 3, 2],
    "price": [
        1200,
        800,
        450,
        200,
        300,
        500,
        100,
        50,
        250,
        700,
        150,
        400,
        1000,
        90,
        60,
        110,
        30,
        1500,
        80,
        600,
    ],
    "sale_date": [
        "2025-03-01",
        "2025-03-02",
        "2025-03-03",
        "2025-03-04",
        "2025-03-05",
        "2025-03-06",
        "2025-03-07",
        "2025-03-08",
        "2025-03-09",
        "2025-03-10",
        "2025-03-11",
        "2025-03-12",
        "2025-03-13",
        "2025-03-14",
        "2025-03-15",
        "2025-03-16",
        "2025-03-17",
        "2025-03-18",
        "2025-03-19",
        "2025-03-20",
    ],
}

df = pd.DataFrame(sales_data)

df.to_sql("sales", conn, if_exists="replace", index=False)

20