<a href="https://colab.research.google.com/github/niginadavronova/collab.works/blob/main/%D0%9A%D0%BE%D0%BF%D0%B8%D1%8F_%D0%B1%D0%BB%D0%BE%D0%BA%D0%BD%D0%BE%D1%82%D0%B0_%22DS_pandas_2_amaliyot_df_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ![Imgur](https://i.imgur.com/5pXzCIu.png)

# **DATA SCIENCE VA SUN'IY INTELLEKT PRAKTIKUM**

## Ma'lumotlar tahlili. Pandas kutubxonasi.

# **AMALIYOT**
## DataFrame

### **1-mashq**. `Pandas` kutubxonasini `pd`, `numpy` kutubxonasini `np` deb chaqirib oling

In [1]:
# Javobni shuyerga yozing
import pandas as pd
import numpy as np

In [ ]:
#@title **To'g'ri javob**
import pandas as pd
import numpy as np

### **2-mashq.** Quyida ko'rsatilgan dataframeni yarating va `df` deb nomlang

In [2]:
# Javobni shuyerga yozing
viloyatlar = [
   "Andijon viloyati", "Buxoro viloyati", "Farg'ona viloyati", "Jizzax viloyati",
    "Xorazm viloyati", "Namangan viloyati", "Navoiy viloyati", "Qashqadaryo viloyati",
    "Qoraqalpogʻiston Respublikasi", "Samarqand viloyati", "Sirdaryo viloyati",
    "Surxondaryo viloyati", "Toshkent viloyati"
]
markazlar = [
   "Andijon shahri", "Buxoro shahri", "Fargona shahri", "Jizzax shahri",
    "Urganch shahri", "Namangan shahri", "Navoiy shahri", "Qarshi shahri",
    "Nukus shahri", "Samarqand shahri", "Guliston shahri", "Termiz ri", "Nurafshon shahri"]

maydonlar = [4200, 39400, 6800, 20500, 6300, 7900, 110800, 28400, 160000, 16400, 5100, 20800, 15300]

aholi = [1899000, 1384700, 2597000, 910500, 1200000, 1862000, 767500, 2029000, 1200000, 2322000, 648100, 1676000, 4450000]

data = {
    "Hudud":viloyatlar,
    "Markaz":markazlar,
    "Maydoni":maydonlar,
    "Aholisi":aholi
}
df = pd.DataFrame(data)
df

                            Hudud            Markaz  Maydoni  Aholisi
0                Andijon viloyati    Andijon shahri     4200  1899000
1                 Buxoro viloyati     Buxoro shahri    39400  1384700
2               Farg'ona viloyati    Fargona shahri     6800  2597000
3                 Jizzax viloyati     Jizzax shahri    20500   910500
4                 Xorazm viloyati    Urganch shahri     6300  1200000
5               Namangan viloyati   Namangan shahri     7900  1862000
6                 Navoiy viloyati     Navoiy shahri   110800   767500
7            Qashqadaryo viloyati     Qarshi shahri    28400  2029000
8   Qoraqalpogʻiston Respublikasi      Nukus shahri   160000  1200000
9              Samarqand viloyati  Samarqand shahri    16400  2322000
10              Sirdaryo viloyati   Guliston shahri     5100   648100
11           Surxondaryo viloyati         Termiz ri    20800  1676000
12              Toshkent viloyati  Nurafshon shahri    15300  4450000

In [ ]:
# @title **To'g'ri javob**
viloyatlar = [
    "Andijon viloyati",
    "Buxoro viloyati",
    "Fargona viloyati",
    "Jizzax viloyati",
    "Xorazm viloyati",
    "Namangan viloyati",
    "Navoiy viloyati",
    "Qashqadaryo viloyati",
    "Qoraqalpogʻiston Respublikasi",
    "Samarqand viloyati",
    "Sirdaryo viloyati",
    "Surxondaryo viloyati",
    "Toshkent viloyati",
]
markazlar = [
    "Andijon shahri",
    "Buxoro shahri",
    "Fargona shahri",
    "Jizzax shahri",
    "Urganch shahri",
    "Namangan shahri",
    "Navoiy shahri",
    "Qarshi shahri",
    "Nukus shahri",
    "Samarqand shahri",
    "Guliston shahri",
    "Termiz shahri",
    "Nurafshon shahri",
]
maydonlar = [
    4200,
    39400,
    6800,
    20500,
    6300,
    7900,
    110800,
    28400,
    160000,
    16400,
    5100,
    20800,
    15300,
]
aholi = [
    1899000,
    1384700,
    2597000,
    910500,
    1200000,
    1862000,
    767500,
    2029000,
    1200000,
    2322000,
    648100,
    1676000,
    4450000,
]
data = {
    "Hudud":viloyatlar,
    "Markaz":markazlar,
    "Maydoni":maydonlar,
    "Aholisi":aholi
}
df = pd.DataFrame(data)
df

NameError: name 'pd' is not defined

### **2-mashq.** Yuqoridagi df ning yuqorisidan 5 ta qator chiqaring

In [6]:
# Javobni shuyerga yozing
df.head()

               Hudud          Markaz  Maydoni  Aholisi
0   Andijon viloyati  Andijon shahri     4200  1899000
1    Buxoro viloyati   Buxoro shahri    39400  1384700
2  Farg'ona viloyati  Fargona shahri     6800  2597000
3    Jizzax viloyati   Jizzax shahri    20500   910500
4    Xorazm viloyati  Urganch shahri     6300  1200000

In [ ]:
#@title **To'g'ri javob**
df.head()

               Hudud          Markaz  Maydoni  Aholisi
0   Andijon viloyati  Andijon shahri     4200  1899000
1    Buxoro viloyati   Buxoro shahri    39400  1384700
2  Farg'ona viloyati  Fargona shahri     6800  2597000
3    Jizzax viloyati   Jizzax shahri    20500   910500
4    Xorazm viloyati  Urganch shahri     6300  1200000

### **3-mashq.** Yuqoridagi df dan tasodifiy 3 ta qator chiqaring

In [7]:
# Javobni shuyerga yozing
df.sample(3)

                Hudud            Markaz  Maydoni  Aholisi
12  Toshkent viloyati  Nurafshon shahri    15300  4450000
5   Namangan viloyati   Namangan shahri     7900  1862000
4     Xorazm viloyati    Urganch shahri     6300  1200000

In [ ]:
#@title **To'g'ri javob**
df.sample(3)

                           Hudud          Markaz  Maydoni  Aholisi
0               Andijon viloyati  Andijon shahri     4200  1899000
3                Jizzax viloyati   Jizzax shahri    20500   910500
8  Qoraqalpogʻiston Respublikasi    Nukus shahri   160000  1200000

### **4-mashq.** Yuqoridagi df ning 'Hudud' va 'Aholisi' ustinlarini alohida df ko'rinishida chiqaring

In [8]:
# Javobni shuyerga yozing
df[['Hudud', 'Aholisi']]

                            Hudud  Aholisi
0                Andijon viloyati  1899000
1                 Buxoro viloyati  1384700
2               Farg'ona viloyati  2597000
3                 Jizzax viloyati   910500
4                 Xorazm viloyati  1200000
5               Namangan viloyati  1862000
6                 Navoiy viloyati   767500
7            Qashqadaryo viloyati  2029000
8   Qoraqalpogʻiston Respublikasi  1200000
9              Samarqand viloyati  2322000
10              Sirdaryo viloyati   648100
11           Surxondaryo viloyati  1676000
12              Toshkent viloyati  4450000

In [ ]:
#@title **To'g'ri javob**
df[['Hudud','Aholisi']]

                            Hudud  Aholisi
0                Andijon viloyati  1899000
1                 Buxoro viloyati  1384700
2               Fargʻona viloyati  2597000
3                 Jizzax viloyati   910500
4                 Xorazm viloyati  1200000
5               Namangan viloyati  1862000
6                 Navoiy viloyati   767500
7            Qashqadaryo viloyati  2029000
8   Qoraqalpogʻiston Respublikasi  1200000
9              Samarqand viloyati  2322000
10              Sirdaryo viloyati   648100
11           Surxondaryo viloyati  1676000
12              Toshkent viloyati  4450000

### **5-mashq.** Yuqoridagi df ning `Markaz` ustunini Series obyekti ko'rinishida chiqaring

In [9]:
# Javobni shuyerga yozing
df.Markaz

0       Andijon shahri
1        Buxoro shahri
2       Fargona shahri
3        Jizzax shahri
4       Urganch shahri
5      Namangan shahri
6        Navoiy shahri
7        Qarshi shahri
8         Nukus shahri
9     Samarqand shahri
10     Guliston shahri
11           Termiz ri
12    Nurafshon shahri
Name: Markaz, dtype: object

In [ ]:
#@title **To'g'ri javob**
df.Markaz

0       Andijon shahri
1        Buxoro shahri
2      Fargʻona shahri
3        Jizzax shahri
4       Urganch shahri
5      Namangan shahri
6        Navoiy shahri
7        Qarshi shahri
8         Nukus shahri
9     Samarqand shahri
10     Guliston shahri
11       Termiz shahri
12    Nurafshon shahri
Name: Markaz, dtype: object

### **6-mashq.** Yuqoridagi df dan aholi soni 2 milliondan oshiq bo'lgan hududlarni chiqaring

In [10]:
# Javobni shuyerga yozing
df[df.Aholisi>2000000]

                   Hudud            Markaz  Maydoni  Aholisi
2      Farg'ona viloyati    Fargona shahri     6800  2597000
7   Qashqadaryo viloyati     Qarshi shahri    28400  2029000
9     Samarqand viloyati  Samarqand shahri    16400  2322000
12     Toshkent viloyati  Nurafshon shahri    15300  4450000

In [ ]:
#@title **To'g'ri javob**
df[df.Aholisi>2_000_000]

                   Hudud            Markaz  Maydoni  Aholisi
2      Fargʻona viloyati   Fargʻona shahri     6800  2597000
7   Qashqadaryo viloyati     Qarshi shahri    28400  2029000
9     Samarqand viloyati  Samarqand shahri    16400  2322000
12     Toshkent viloyati  Nurafshon shahri    15300  4450000

### **7-mashq.** Yuqoridagi df dan maydoni 10000kv.km dan kichik bo'lgan hududlarni chiqaring

In [11]:
# Javobni shuyerga yozing
df[df.Maydoni<10000]

                Hudud           Markaz  Maydoni  Aholisi
0    Andijon viloyati   Andijon shahri     4200  1899000
2   Farg'ona viloyati   Fargona shahri     6800  2597000
4     Xorazm viloyati   Urganch shahri     6300  1200000
5   Namangan viloyati  Namangan shahri     7900  1862000
10  Sirdaryo viloyati  Guliston shahri     5100   648100

In [ ]:
#@title **To'g'ri javob**
df[df.Maydoni<10000]

                Hudud           Markaz  Maydoni  Aholisi
0    Andijon viloyati   Andijon shahri     4200  1899000
2    Fargona viloyati   Fargona shahri     6800  2597000
4     Xorazm viloyati   Urganch shahri     6300  1200000
5   Namangan viloyati  Namangan shahri     7900  1862000
10  Sirdaryo viloyati  Guliston shahri     5100   648100

### **8-mashq.** Yuqoridagi df ning birinchi ustunini df ning indeksi sifatida ishlating
Ishora:
1. Yoki df ni qayta yarating
2. Yoki `set_index()` metodidan foydalaning

In [22]:
# Javobni shuyerga yozing
df.set_index(df.columns[0], inplace=True)
df.head()

                           Markaz  Maydoni  Aholisi
Hudud
Andijon viloyati   Andijon shahri     4200  1899000
Buxoro viloyati     Buxoro shahri    39400  1384700
Farg'ona viloyati  Fargona shahri     6800  2597000
Jizzax viloyati     Jizzax shahri    20500   910500
Xorazm viloyati    Urganch shahri     6300  1200000

In [7]:
#@title **To'g'ri javob**
df.set_index(df.columns[0], inplace=True)
df.head()

                           Markaz  Maydoni  Aholisi
Hudud
Andijon viloyati   Andijon shahri     4200  1899000
Buxoro viloyati     Buxoro shahri    39400  1384700
Farg'ona viloyati  Fargona shahri     6800  2597000
Jizzax viloyati     Jizzax shahri    20500   910500
Xorazm viloyati    Urganch shahri     6300  1200000

### **9-mashq.** Yuqoridagi df dan, Aholisi 2 milliondan oshiq hududlar orasida Samarqand viloyati bor yoki yo'qligini tekshiring

In [13]:
# Javobni shuyerga yozing
'Samarqand viloyati' in df[df.Aholisi>2_000_000].index

True

In [ ]:
#@title **To'g'ri javob**
"Samarqand viloyati" in df[df.Aholisi>2_000_000].index

True

### **10-mashq.**  Yuqoridagi df dan faqatgina Andijon, Farg'ona va Namangan viloyatlarini ajratib ko'rsating

In [14]:
# Javobni shuyerga yozing
df.loc[['Andijon viloyati',"Farg'ona viloyati",'Namangan viloyati']]

                            Markaz  Maydoni  Aholisi
Hudud
Andijon viloyati    Andijon shahri     4200  1899000
Farg'ona viloyati   Fargona shahri     6800  2597000
Namangan viloyati  Namangan shahri     7900  1862000

In [ ]:
#@title **To'g'ri javob**
df.loc[["Andijon viloyati","Fargona viloyati","Namangan viloyati"]]

                            Markaz  Maydoni  Aholisi
Hudud
Andijon viloyati    Andijon shahri     4200  1899000
Fargona viloyati    Fargona shahri     6800  2597000
Namangan viloyati  Namangan shahri     7900  1862000

### **11-mashq.**  Yuqoridagi df dan Samarqanda va Toshkent viloyatlarining aholisi va maydonini alohida df ko'rinishida chiqaring

In [15]:
# Javobni shuyerga yozing
df.loc[['Samarqand viloyati', 'Toshkent viloyati'],['Aholisi', 'Maydoni']]

                    Aholisi  Maydoni
Hudud
Samarqand viloyati  2322000    16400
Toshkent viloyati   4450000    15300

In [ ]:
#@title **To'g'ri javob**
df.loc[['Toshkent viloyati','Samarqand viloyati'],['Maydoni','Aholisi']]

                    Maydoni  Aholisi
Hudud
Toshkent viloyati     15300  4450000
Samarqand viloyati    16400  2322000

### **12-mashq.**  Yuqoridagi df dan yangi df_new DataFrame yarating. Yangi dataframega faqatgina aholisi 1.5mln dan kam bo'lgan hududlarni ko'chiring.

In [21]:
# Javobni shuyerga yozing
df_new=df[df.Aholisi<1500000]
df_new

                            Hudud           Markaz  Maydoni  Aholisi
1                 Buxoro viloyati    Buxoro shahri    39400  1384700
3                 Jizzax viloyati    Jizzax shahri    20500   910500
4                 Xorazm viloyati   Urganch shahri     6300  1200000
6                 Navoiy viloyati    Navoiy shahri   110800   767500
8   Qoraqalpogʻiston Respublikasi     Nukus shahri   160000  1200000
10              Sirdaryo viloyati  Guliston shahri     5100   648100

In [5]:
#@title **To'g'ri javob**
df_new = df[df.Aholisi<1_500_000]
df_new

                            Hudud           Markaz  Maydoni  Aholisi
1                 Buxoro viloyati    Buxoro shahri    39400  1384700
3                 Jizzax viloyati    Jizzax shahri    20500   910500
4                 Xorazm viloyati   Urganch shahri     6300  1200000
6                 Navoiy viloyati    Navoiy shahri   110800   767500
8   Qoraqalpogʻiston Respublikasi     Nukus shahri   160000  1200000
10              Sirdaryo viloyati  Guliston shahri     5100   648100

### **13-mashq.**  Yangi df qatorlari orasida Navoiy, Namangan va Xorazm viloyatlari borligini tekshiring

In [9]:
# Javobni shuyerga yozing
'Navoiy viloyati', 'Namangan viloyati', 'Xorazm viloyati' in df_new.index

('Navoiy viloyati', 'Namangan viloyati', True)

In [ ]:
#@title **To'g'ri javob**
pd.Index(['Navoiy viloyati','Namangan viloyati','Xorazm viloyati']).isin(df_new.index)

array([ True, False,  True])

### **14-mashq.**  Aholisi 1milliondan ko'p, lekin maydoni 10000kv.km dan kam hududlarni chiqaring

In [10]:
# Javobni shuyerga yozing
df=pd.DataFrame(data)
df[(df.Aholisi>1_000_000) & (df.Maydoni<10000)]

               Hudud           Markaz  Maydoni  Aholisi
0   Andijon viloyati   Andijon shahri     4200  1899000
2  Farg'ona viloyati   Fargona shahri     6800  2597000
4    Xorazm viloyati   Urganch shahri     6300  1200000
5  Namangan viloyati  Namangan shahri     7900  1862000

In [11]:
#@title **To'g'ri javob**
df[(df.Aholisi>1_000_000) & (df.Maydoni<10000)]

               Hudud           Markaz  Maydoni  Aholisi
0   Andijon viloyati   Andijon shahri     4200  1899000
2  Farg'ona viloyati   Fargona shahri     6800  2597000
4    Xorazm viloyati   Urganch shahri     6300  1200000
5  Namangan viloyati  Namangan shahri     7900  1862000

### **15-mashq.**  Aholisi 1milliondan kam, lekin maydoni 10000kv.km dan ko'p hududlarni chiqaring

In [12]:
# Javobni shuyerga yozing
df[(df.Aholisi<1_000_000) & (df.Maydoni>10000)]

             Hudud         Markaz  Maydoni  Aholisi
3  Jizzax viloyati  Jizzax shahri    20500   910500
6  Navoiy viloyati  Navoiy shahri   110800   767500

In [13]:
#@title **To'g'ri javob**
df[(df.Aholisi<1_000_000) & (df.Maydoni>10000)]

             Hudud         Markaz  Maydoni  Aholisi
3  Jizzax viloyati  Jizzax shahri    20500   910500
6  Navoiy viloyati  Navoiy shahri   110800   767500

### **16-mashq.**  Yuqoridagi df dan `Markaz` ustunini tashlab yuboring

In [14]:
# Javobni shuyerga yozing
df.drop(['Markaz'],axis=1)

                            Hudud  Maydoni  Aholisi
0                Andijon viloyati     4200  1899000
1                 Buxoro viloyati    39400  1384700
2               Farg'ona viloyati     6800  2597000
3                 Jizzax viloyati    20500   910500
4                 Xorazm viloyati     6300  1200000
5               Namangan viloyati     7900  1862000
6                 Navoiy viloyati   110800   767500
7            Qashqadaryo viloyati    28400  2029000
8   Qoraqalpogʻiston Respublikasi   160000  1200000
9              Samarqand viloyati    16400  2322000
10              Sirdaryo viloyati     5100   648100
11           Surxondaryo viloyati    20800  1676000
12              Toshkent viloyati    15300  4450000

In [15]:
#@title **To'g'ri javob**
df.drop(['Markaz'], axis=1)

                            Hudud  Maydoni  Aholisi
0                Andijon viloyati     4200  1899000
1                 Buxoro viloyati    39400  1384700
2               Farg'ona viloyati     6800  2597000
3                 Jizzax viloyati    20500   910500
4                 Xorazm viloyati     6300  1200000
5               Namangan viloyati     7900  1862000
6                 Navoiy viloyati   110800   767500
7            Qashqadaryo viloyati    28400  2029000
8   Qoraqalpogʻiston Respublikasi   160000  1200000
9              Samarqand viloyati    16400  2322000
10              Sirdaryo viloyati     5100   648100
11           Surxondaryo viloyati    20800  1676000
12              Toshkent viloyati    15300  4450000

In [25]:
df

                            Hudud            Markaz  Maydoni  Aholisi
0                Andijon viloyati    Andijon shahri     4200  1899000
1                 Buxoro viloyati     Buxoro shahri    39400  1384700
2               Farg'ona viloyati    Fargona shahri     6800  2597000
3                 Jizzax viloyati     Jizzax shahri    20500   910500
4                 Xorazm viloyati    Urganch shahri     6300  1200000
5               Namangan viloyati   Namangan shahri     7900  1862000
6                 Navoiy viloyati     Navoiy shahri   110800   767500
7            Qashqadaryo viloyati     Qarshi shahri    28400  2029000
8   Qoraqalpogʻiston Respublikasi      Nukus shahri   160000  1200000
9              Samarqand viloyati  Samarqand shahri    16400  2322000
10              Sirdaryo viloyati   Guliston shahri     5100   648100
11           Surxondaryo viloyati         Termiz ri    20800  1676000
12              Toshkent viloyati  Nurafshon shahri    15300  4450000

### **17-mashq.**  Yuqoridagi df dan Sirdaryo viloyati aholisini chiqaring

In [16]:
# Javobni shuyerga yozing
df_new.at['Sirdaryo viloyati','Aholisi']

np.int64(648100)

In [27]:
#@title **To'g'ri javob**
df_new.at['Sirdaryo viloyati','Aholisi']

np.int64(648100)

### **18-mashq.**  Yuqoridagi df dan Buxoro viloyati maydonini chiqaring

In [17]:
# Javobni shuyerga yozing
df_new.at['Buxoro viloyati', 'Maydoni']

np.int64(39400)

In [ ]:
#@title **To'g'ri javob**
df.at['Buxoro viloyati','Maydoni']

39400

### **19-mashq.**  Yuqoridagi df dan Toshkent viloyati maydoni O'zbekiston Respublikasining necha fozini tashkil qilishini toping

In [23]:
# Javobni shuyerga yozing
tosh_area = df.at['Toshkent viloyati','Maydoni']
uzb_area = sum(df.Maydoni) # yoki
# uzb_area = df.Maydoni.sum()
print(f"Toshkent viloyati maydoni: {tosh_area} kv.km")
print(f"O'zbekiston Respublikasi maydoni: {uzb_area} kv.km")
print(f"Toshkent viloyati maydoni O'zbekiston respublikasining {round(tosh_area/uzb_area*100)}% ni tashkil qiladi")

Toshkent viloyati maydoni: 15300 kv.km
O'zbekiston Respublikasi maydoni: 441900 kv.km
Toshkent viloyati maydoni O'zbekiston respublikasining 3% ni tashkil qiladi

In [25]:
#@title **To'g'ri javob**
tosh_area = df.at['Toshkent viloyati','Maydoni']
uzb_area = sum(df.Maydoni)
print(f"Toshkent viloyati maydoni: {tosh_area} kv.km")
print(f"O'zbekiston Respublikasi maydoni: {uzb_area} kv.km")
print(f"Toshkent viloyati maydoni O'zbekiston respublikasining {round(tosh_area/uzb_area*100)}% ni tashkil qiladi")

Toshkent viloyati maydoni: 15300 kv.km
O'zbekiston Respublikasi maydoni: 441900 kv.km
Toshkent viloyati maydoni O'zbekiston respublikasining 3% ni tashkil qiladi

### **20-mashq.**  Yuqoridagi df dan Toshkent viloyati aholisi O'zbekiston Respublikasining necha fozini tashkil qilishini toping

In [24]:
# Javobni shuyerga yozing
tosh_area = df.at['Toshkent viloyati','Aholisi']
uzb_area = sum(df.Aholisi)
print(f"Toshkent viloyati aholisi: {tosh_area} kishi")
print(f"O'zbekiston Respublikasi aholisi: {uzb_area} kishi")
print(f"Toshkent viloyati aholisi O'zbekiston respublikasining {round(tosh_area/uzb_area*100)}% ni tashkil qiladi")

Toshkent viloyati aholisi: 4450000 kishi
O'zbekiston Respublikasi aholisi: 22945800 kishi
Toshkent viloyati aholisi O'zbekiston respublikasining 19% ni tashkil qiladi

In [ ]:
#@title **To'g'ri javob**
tosh_area = df.at['Toshkent viloyati','Aholisi']
uzb_area = sum(df.Aholisi) # yoki
# uzb_area = df.Maydoni.sum()
print(f"Toshkent viloyati aholisi: {tosh_area} kishi")
print(f"O'zbekiston Respublikasi aholisi: {uzb_area} kishi")
print(f"Toshkent viloyati aholisi O'zbekiston respublikasining {round(tosh_area/uzb_area*100)}% ni tashkil qiladi")

Toshkent viloyati aholisi: 4450000 kishi
O'zbekiston Respublikasi aholisi: 22945800 kishi
Toshkent viloyati aholisi O'zbekiston respublikasining 19% ni tashkil qiladi